### PR TITLE
Revise unit-test names

### PR DESCRIPTION
**Pull request by supl**
This PR revises unit-test case names to conform to with the following pattern

- Test_{function}
- Test_{type}_{function for the type}

For example, assuming a package `p` that defines a type `T`, a function `TF` for the type `T`, and a function `F` for the package `p` in this file,

```go
package p

type T int

func F() {
}

func (t T) TF {
}
```
then the test cases can be named as `Test_T_TF` and `Test_F`.

```
package p

import "testing"

func TestT_TF(tester *testing.T) {
}

func TestF(tester *testing.T) {
}
```

The error report (if happens) from running the test can directly and clearly address where the error happens.

### CODE REVIEW

**Review by thongdk8 — APPROVED** [review]
LGTM! Thank you!
Left a question but it does block the PR being merged: With this pattern, do we need a specific postfix for each when we have multiple tests for a function?

**Review by ypeckstadt — APPROVED** [review]
LGTM! Thank you!

**Review by feeblefakie — COMMENTED** [review]
Thank you! Is it following common go conventions?

**Comment by supl** [comment]
> LGTM! Thank you! Left a question but it does block the PR being merged: With this pattern, do we need a specific postfix for each when we have multiple tests for a function?

@thongdk8 
Thanks for your question.
I will put them into the same function.
(One function includes more than one test case)

I try not to use suffixes to simplify the code but if a test case is too complicated, I will consider using it.

ref: https://pkg.go.dev/testing#hdr-Examples

**Comment by supl** [comment]
> Thank you! Is it following common go conventions?

@feeblefakie 
Actually, I did a study again.
I found there is an example of naming the test cases in the testing package.
https://pkg.go.dev/testing#hdr-Examples

So, I would like to revise the patter from

```
package p

import "testing"

func Test_T_TF(tester *testing.T) {
}

func Test_F(tester *testing.T) {
}
```

to

```
package p

import "testing"

func TestT_TF(tester *testing.T) {
}

func TestF(tester *testing.T) {
}
```

**Comment by supl** [comment]
@feeblefakie 
I revised the naming again in https://github.com/scalar-labs/scalardl-go-client-sdk/pull/15/commits/2169acd11e0a2099de8904ea6bbc520860955acb
Please kindly check it when you have a chance.
Thank you!

**Review by feeblefakie — APPROVED** [review]
LGTM! Thank you!

**Pull request merged**
