### PR TITLE
Skeleton

### PR DESCRIPTION
**Pull request by supl**
This PR provides the skeleton of Scalar DL Go Client SDK.

- The gRPC-generated files
- Apache 3.0 LICENSE
- README for how to generate the gRPC related files

The Go module name is `github.com/scalar-labs/dl`.

The gRPC-generated files are defined as the package `rpc`.
The import path is `github.com/scalar-labs/dl/rpc` (module + package)

The ClientService interface is planned to be put in the package `client` (the full import path will be `github.com/scalar-labs/dl/client`

The use in the application will be like this
```
import "github.com/scalar-labs/dl/client"

func main() {
        var clientService client.ClientService
}
```

### CODE REVIEW

**Comment by feeblefakie** [comment]
@ypeckstadt @thongdk8 I'm not very familiar with go so please review this PR and the PRs coming afterwards.

**Review by ypeckstadt — APPROVED** [review]
@feeblefakie I Wil do from now on. Thanks.
LGTM

**Comment by feeblefakie** [comment]
@thongdk8 Can you take a look?

**Review by feeblefakie — APPROVED** [review]
LGTM! Thank you!

**Review by thongdk8 — APPROVED** [review]
Sorry for the late review. LGTM! Thank you!

**Comment by supl** [comment]
Thank you, everyone.
I will merge it.

**Pull request merged**
