### PR TITLE
config package (ClientConfig) Implementation

### PR DESCRIPTION
**Pull request by supl**
This PR implements the `ClientConfig` structure.
It now supports load config from JSON or Java properties.

This implementation uses two MIT-licensed 3rd-party packages
- [validator](https://github.com/go-playground/validator) (to validate the ClientConfig structure)
- [viper](https://github.com/spf13/viper) (to parse the Java Properties files and the JSON files)

Example:
```
var clientConfig ClientConfig
var err error

var javaProperties string = `
scalar.dl.client.cert_holder_id=foo
scalar.dl.client.cert_pem=cert_pem
scalar.dl.client.private_key_pem=private_key_pem
`

var json string = `
{
	"scalar.dl.client.cert_holder_id": "foo",
	"scalar.dl.client.cert_pem": "cert_pem",
	"scalar.dl.client.private_key_pem": "private_key_pem"
}
`

if clientConfig, err = NewClientConfigFromJavaProperties(javaProperties); err != nil {
        // can't parse the .properties file
}
	
if err = clientConfig.Validate(); err != nil {
        // the clientConfig instance is invalid
}
	
// use clientConfig
```

### CODE REVIEW

**Comment by supl** [comment]
@feeblefakie 
@thongdk8 
@ypeckstadt 
Please take a look when you have time.
Thank you :)

**Review by ypeckstadt — APPROVED** [review]
LGTM.  @supl One small comment though, well actually more of a question. What kind of documentation will be provided for the code/client afterwards?   If you will use Godoc, maybe it's better to already add the comments now to spare yourself the work of having to go through the code at the end to document it.  Although so far the code is pretty much self-explanatory.

**Review by thongdk8 — APPROVED** [review]
LGTM! Thank you!

**Comment by supl** [comment]
> LGTM. @supl One small comment though, well actually more of a question. What kind of documentation will be provided for the code/client afterwards? If you will use Godoc, maybe it's better to already add the comments now to spare yourself the work of having to go through the code at the end to document it. Although so far the code is pretty much self-explanatory.

I will mainly use README.md but I think you are right.
godoc helps when the module is discoverable on pkg.go.dev.
I will do that now.

**Comment by supl** [comment]
@ypeckstadt 
I added godoc for the config package [here](https://github.com/scalar-labs/scalardl-go-client-sdk/pull/3/commits/bbfa835de1beea24f1fa0dd35356b92b1ab4a815).
Thanks for your feedback :)

**Review by feeblefakie — APPROVED** [review]
LGTM! Thank you!

**Review by ypeckstadt — APPROVED** [review]
LGTM. Thank you.

**Pull request merged**
